import Command from "../command";
import { rand, roll } from "../utils";

const ratingIndex = (cr: number) => {
    if (cr <= 4) {
        return 0;
    }
    if (cr <= 10) {
        return 1;
    }
    if (cr <= 16) {
        return 2;
    }
    return 3;
};

const individualTable = [
    [ // CR 0-4
        ...new Array(30).fill({"cp": "5d6"}),
        ...new Array(30).fill({"sp": "5d6"}),
        ...new Array(10).fill({"ep": "3d6"}),
        ...new Array(25).fill({"gp": "3d6"}),
        ...new Array(5).fill({"pp": "1d6"}),
    ],
    [ // CR 5-10
        ...new Array(30).fill({"cp": "4d6×100", "ep": "1d6×10"}),
        ...new Array(30).fill({"sp": "6d6×10", "gp": "2d6×10"}),
        ...new Array(10).fill({"ep": "3d6x10", "gp": "2d6×10"}),
        ...new Array(25).fill({"gp": "4d6×10"}),
        ...new Array(5).fill({"gp": "2d6×10", "pp": "3d6"}),
    ],
    [ // CR 11-16
        ...new Array(20).fill({"sp": "4d6×100", "gp": "1d6×100"}),
        ...new Array(15).fill({"ep": "1d6×100", "gp": "1d6×100"}),
        ...new Array(40).fill({"gp": "2d6×100", "pp": "1d6×10"}),
        ...new Array(25).fill({"gp": "2d6×100", "pp": "2d6×10"}),
    ],
    [ // CR 17+
        ...new Array(15).fill({"ep": "2d6×1000", "gp": "8d6×100"}),
        ...new Array(40).fill({"gp": "1d6×1000", "pp": "1d6×100"}),
        ...new Array(45).fill({"gp": "1d6×1000", "pp": "2d6×100"}),
    ],
];

const magicTableA = [
    ...new Array(50).fill("Potion of healing"),
    "Spell scroll (Control Flames)",
    "Spell scroll (Create Bonfire)",
    "Spell scroll (Dancing Lights)",
    "Spell scroll (Encode Thoughts)",
    "Spell scroll (Magic Stone)",
    "Spell scroll (Minor Illusion)",
    "Spell scroll (Mold Earth)",
    "Spell scroll (Produce Flame)",
    "Spell scroll (Shape Water)",
    "Spell scroll (Word of Radiance)",
    ...new Array(10).fill("Potion of climbing"),
    "Spell scroll (1st)",
    "Spell scroll (1st)",
    "Spell scroll (1st)",
    "Spell scroll (1st)",
    "Spell scroll (1st)",
    "Spell scroll (1st)",
    "Spell scroll (1st)",
    "Spell scroll (1st)",
    "Spell scroll (1st)",
    "Spell scroll (1st)",
    "Spell scroll (1st)",
    "Spell scroll (1st)",
    "Spell scroll (1st)",
    "Spell scroll (1st)",
    "Spell scroll (1st)",
    "Spell scroll (1st)",
    "Spell scroll (1st)",
    "Spell scroll (1st)",
    "Spell scroll (1st)",
    "Spell scroll (1st)",
    "Spell scroll (2nd)",
    "Spell scroll (2nd)",
    "Spell scroll (2nd)",
    "Spell scroll (2nd)",
    "Spell scroll (2nd)",
    ...new Array(3).fill("Potion of healing (greater)"),
    "Bag of holding",
    "Driftglobe",
];

const magicTableB = [
    ...new Array(15).fill("Potion of healing (greater)"),
    ...new Array(7).fill("Potion of fire breath"),
    ...new Array(7).fill("Potion of resistance"),
    ...new Array(5).fill("Ammunition, +1"),
    ...new Array(5).fill("Potion of animal friendship"),
    ...new Array(5).fill("Potion of hill giant strength"),
    ...new Array(5).fill("Potion of growth"),
    ...new Array(5).fill("Potion of water breathing"),
    "Spell scroll (2nd)",
    "Spell scroll (2nd)",
    "Spell scroll (2nd)",
    "Spell scroll (2nd)",
    "Spell scroll (2nd)",
    "Spell scroll (3rd)",
    "Spell scroll (3rd)",
    "Spell scroll (3rd)",
    "Spell scroll (3rd)",
    "Spell scroll (3rd)",
    ...new Array(3).fill("Bag of holding"),
    ...new Array(3).fill("Keoghtom’s ointment"),
    ...new Array(3).fill("Oil of slipperiness"),
    ...new Array(2).fill("Dust of disappearance"),
    ...new Array(2).fill("Dust of dryness"),
    ...new Array(2).fill("Dust of sneezing and choking"),
    ...new Array(2).fill("Elemental gem"),
    ...new Array(2).fill("Philter of love"),
    "Alchemy jug",
    "Cap of water breathing",
    "Cloak of the manta ray",
    "Driftglobe",
    "Goggles of night",
    "Helm of comprehending languages",
    "Immovable rod",
    "Lantern of revealing",
    "Mariner’s armor",
    "Mithral armor",
    "Potion of poison",
    "Ring of swimming",
    "Robe of useful items",
    "Rope of climbing",
    "Saddle of the cavalier",
    "Wand of magic detection",
    "Wand of secrets",
];

const magicTableC = [
    ...new Array(15).fill("Potion of healing (superior)"),
    "Spell scroll (4th)",
    "Spell scroll (4th)",
    "Spell scroll (4th)",
    "Spell scroll (4th)",
    "Spell scroll (4th)",
    "Spell scroll (4th)",
    "Spell scroll (4th)",
    ...new Array(5).fill("Ammunition, +2"),
    ...new Array(5).fill("Potion of clairvoyance"),
    ...new Array(5).fill("Potion of diminution"),
    ...new Array(5).fill("Potion of gaseous form"),
    ...new Array(5).fill("Potion of frost giant strength"),
    ...new Array(5).fill("Potion of stone giant strength"),
    ...new Array(5).fill("Potion of heroism"),
    ...new Array(5).fill("Potion of invulnerability"),
    ...new Array(5).fill("Potion of mind reading"),
    "Spell scroll (5th)",
    "Spell scroll (5th)",
    "Spell scroll (5th)",
    "Spell scroll (5th)",
    "Spell scroll (5th)",
    ...new Array(3).fill("Elixir of health"),
    ...new Array(3).fill("Oil of etherealness"),
    ...new Array(3).fill("Potion of fire giant strength"),
    ...new Array(3).fill("Quaal’s feather token"),
    ...new Array(3).fill("Scroll of protection"),
    ...new Array(2).fill("Bag of beans"),
    ...new Array(2).fill("Bead of force"),
    "Chime of opening",
    "Decanter of endless water",
    "Eyes of minute seeing",
    "Folding boat",
    "Heward’s handy haversack",
    "Horseshoes of speed",
    "Necklace of fireballs",
    "Periapt of health",
    "Sending stones",
];

const magicTableD = [
    ...new Array(20).fill("Potion of healing (supreme)"),
    ...new Array(10).fill("Potion of invisibility"),
    ...new Array(10).fill("Potion of speed"),
    "Spell scroll (6th)",
    "Spell scroll (6th)",
    "Spell scroll (6th)",
    "Spell scroll (6th)",
    "Spell scroll (6th)",
    "Spell scroll (6th)",
    "Spell scroll (6th)",
    "Spell scroll (6th)",
    "Spell scroll (6th)",
    "Spell scroll (6th)",
    "Spell scroll (7th)",
    "Spell scroll (7th)",
    "Spell scroll (7th)",
    "Spell scroll (7th)",
    "Spell scroll (7th)",
    "Spell scroll (7th)",
    "Spell scroll (7th)",
    ...new Array(5).fill("Ammunition, +3"),
    ...new Array(5).fill("Oil of sharpness"),
    ...new Array(5).fill("Potion of flying"),
    ...new Array(5).fill("Potion of cloud giant strength"),
    ...new Array(5).fill("Potion of longevity"),
    ...new Array(5).fill("Potion of vitality"),
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    ...new Array(3).fill("Horseshoes of a zephyr"),
    ...new Array(3).fill("Nolzur’s marvelous pigments"),
    "Bag of devouring",
    "Portable hole",
];

const magicTableE = [
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    "Spell scroll (8th)",
    ...new Array(25).fill("Potion of storm giant strength"),
    ...new Array(15).fill("Potion of healing (supreme)"),
    "Spell scroll (9th)",
    "Spell scroll (9th)",
    "Spell scroll (9th)",
    "Spell scroll (9th)",
    "Spell scroll (9th)",
    "Spell scroll (9th)",
    "Spell scroll (9th)",
    "Spell scroll (9th)",
    "Spell scroll (9th)",
    "Spell scroll (9th)",
    "Spell scroll (9th)",
    "Spell scroll (9th)",
    "Spell scroll (9th)",
    "Spell scroll (9th)",
    "Spell scroll (9th)",
    ...new Array(8).fill("Universal solvent"),
    ...new Array(5).fill("Arrow of slaying"),
    ...new Array(2).fill("Sovereign glue"),
];

const magicTableF = [
    "Club, +1",
    "Dagger, +1",
    "Handaxe, +1",
    "Mace, +1",
    "Quarterstaff, +1",
    "Shortbow, +1",
    "Greatsword, +1",
    "Longsword, +1",
    "Rapier, +1",
    "Shortsword, +1",
    "Longbow, +1",
    "Crossbow, hand +1",
    "Warhammer, +1",
    "Greataxe, +1",
    "Scimitar, +1",
    ...new Array(3).fill("Shield, +1"),
    ...new Array(3).fill("Sentinel shield"),
    ...new Array(2).fill("Amulet of proof against detection and location"),
    ...new Array(2).fill("Boots of elvenkind"),
    ...new Array(2).fill("Boots of striding and springing"),
    ...new Array(2).fill("Bracers of archery"),
    ...new Array(2).fill("Brooch of shielding"),
    ...new Array(2).fill("Broom of flying"),
    ...new Array(2).fill("Cloak of elvenkind"),
    ...new Array(2).fill("Cloak of protection"),
    ...new Array(2).fill("Gauntlets of ogre power"),
    ...new Array(2).fill("Hat of disguise"),
    ...new Array(2).fill("Javelin of lightning"),
    ...new Array(2).fill("Pearl of power"),
    ...new Array(2).fill("Rod of the pact keeper, +1"),
    ...new Array(2).fill("Slippers of spider climbing"),
    ...new Array(2).fill("Staff of the adder"),
    ...new Array(2).fill("Staff of the python"),
    ...new Array(2).fill("Sword of vengeance"),
    ...new Array(2).fill("Trident of fish command"),
    ...new Array(2).fill("Wand of magic missiles"),
    ...new Array(2).fill("Wand of the war mage, +1"),
    ...new Array(2).fill("Wand of web"),
    ...new Array(2).fill("Weapon of warning"),
    "Adamantine armor (chain mail)",
    "Adamantine armor (chain shirt)",
    "Adamantine armor (scale mail)",
    "Bag of tricks (gray)",
    "Bag of tricks (rust)",
    "Bag of tricks (tan)",
    "Boots of the winterlands",
    "Circlet of blasting",
    "Deck of illusions",
    "Eversmoking bottle",
    "Eyes of charming",
    "Eyes of the eagle",
    "Figurine of wondrous power (silver raven)",
    "Gem of brightness",
    "Gloves of missile snaring",
    "Gloves of swimming and climbing",
    "Gloves of thievery",
    "Headband of intellect",
    "Helm of telepathy",
    "Instrument of the bards (Doss lute)",
    "Instrument of the bards (Fochlucan bandore)",
    "Instrument of the bards (Mac-Fuimidh cittern)",
    "Medallion of thoughts",
    "Necklace of adaptation",
    "Periapt of wound closure",
    "Pipes of haunting",
    "Pipes of the sewers",
    "Ring of jumping",
    "Ring of mind shielding",
    "Ring of warmth",
    "Ring of water walking",
    "Quiver of Ehlonna",
    "Stone of good luck (luckstone)",
    "Wind fan",
    "Winged boots",
];

const magicTableG = [
    ...new Array(11).fill("Weapon, +2"),
    ...new Array(3).fill("Figurine of wondrous power (1:Bronze griffon, 2: Ebony fly, 3: Golden lion, 4: Ivory goat, 5: Marble elephant, 6-7: Onyx dog, 8: Serpentine owl"),
    "Adamantine armor (breastplate)",
    "Adamantine armor (splint)",
    "Amulet of health",
    "Armor of vulnerability",
    "Arrow-catching shield",
    "Belt of dwarvenkind",
    "Belt of hill giant strength",
    "Berserker axe",
    "Boots of levitation",
    "Boots of speed",
    "Bowl of commanding water elementals",
    "Bracers of defense",
    "Brazier of commanding fire elementals",
    "Cape of the mountebank",
    "Censer of controlling air elementals",
    "Armor, +1 chain mail",
    "Armor of resistance (chain mail)",
    "Armor, +1 chain shirt",
    "Armor of resistance (chain shirt)",
    "Cloak of displacement",
    "Cloak of the bat",
    "Cube of force",
    "Daern’s instant fortress",
    "Dagger of venom",
    "Dimensional shackles",
    "Dragon slayer",
    "Elven chain",
    "Flame tongue",
    "Gem of seeing",
    "Giant slayer",
    "Glamoured studded leather",
    "Helm of teleportation",
    "Horn of blasting",
    "Horn of Valhalla (silver or brass)",
    "Instrument of the bards (Canaith mandolin)",
    "Instrument of the bards (Cli lyre)",
    "Ioun stone (awareness)",
    "Ioun stone (protection)",
    "Ioun stone (reserve)",
    "Ioun stone (sustenance)",
    "Iron bands of Bilarro",
    "Armor, +1 leather",
    "Armor of resistance (leather)",
    "Mace of disruption",
    "Mace of smiting",
    "Mace of terror",
    "Mantle of spell resistance",
    "Necklace of prayer beads",
    "Periapt of proof against poison",
    "Ring of animal influence",
    "Ring of evasion",
    "Ring of feather falling",
    "Ring of free action",
    "Ring of protection",
    "Ring of resistance",
    "Ring of spell storing",
    "Ring of the ram",
    "Ring of X-ray vision",
    "Robe of eyes",
    "Rod of rulership",
    "Rod of the pact keeper, +2",
    "Rope of entanglement",
    "Armor, +1 scale mail",
    "Armor of resistance (scale mail)",
    "Shield, +2",
    "Shield of missile attraction",
    "Staff of charming",
    "Staff of healing",
    "Staff of swarming insects",
    "Staff of the woodlands",
    "Staff of withering",
    "Stone of controlling earth elementals",
    "Sun blade",
    "Sword of life stealing",
    "Sword of wounding",
    "Tentacle rod",
    "Vicious weapon",
    "Wand of binding",
    "Wand of enemy detection",
    "Wand of fear",
    "Wand of fireballs",
    "Wand of lightning bolts",
    "Wand of paralysis",
    "Wand of the war mage, +2",
    "Wand of wonder",
    "Wings of flying",
];

const magicTableH = [
    ...new Array(10).fill("Weapon, +3"),
    ...new Array(2).fill("Amulet of the planes"),
    ...new Array(2).fill("Carpet of flying"),
    ...new Array(2).fill("Crystal ball (very rare version)"),
    ...new Array(2).fill("Ring of regeneration"),
    ...new Array(2).fill("Ring of shooting stars"),
    ...new Array(2).fill("Ring of telekinesis"),
    ...new Array(2).fill("Robe of scintillating colors"),
    ...new Array(2).fill("Robe of stars"),
    ...new Array(2).fill("Rod of absorption"),
    ...new Array(2).fill("Rod of alertness"),
    ...new Array(2).fill("Rod of security"),
    ...new Array(2).fill("Rod of the pact keeper, +3"),
    ...new Array(2).fill("Scimitar of speed"),
    ...new Array(2).fill("Shield, +3"),
    ...new Array(2).fill("Staff of fire"),
    ...new Array(2).fill("Staff of frost"),
    ...new Array(2).fill("Staff of power"),
    ...new Array(2).fill("Staff of striking"),
    ...new Array(2).fill("Staff of thunder and lightning"),
    ...new Array(2).fill("Sword of sharpness"),
    ...new Array(2).fill("Wand of polymorph"),
    ...new Array(2).fill("Wand of the war mage, +3"),
    "Adamantine armor (half plate)",
    "Adamantine armor (plate)",
    "Animated shield",
    "Belt of fire giant strength",
    "Belt of frost giant strength (or stone)",
    "Armor, +1 breastplate",
    "Armor of resistance (breastplate)",
    "Candle of invocation",
    "Armor, +2 chain mail",
    "Armor, +2 chain shirt",
    "Cloak of arachnida",
    "Dancing sword",
    "Demon armor",
    "Dragon scale mail",
    "Dwarven plate",
    "Dwarven thrower",
    "Efreeti bottle",
    "Figurine of wondrous power (obsidian steed)",
    "Frost brand",
    "Helm of brilliance",
    "Horn of Valhalla (bronze)",
    "Instrument of the bards (Anstruth harp)",
    "Ioun stone (absorption)",
    "Ioun stone (agility)",
    "Ioun stone (fortitude)",
    "Ioun stone (insight)",
    "Ioun stone (intellect)",
    "Ioun stone (leadership)",
    "Ioun stone (strength)",
    "Armor, +2 leather",
    "Manual of bodily health",
    "Manual of gainful exercise",
    "Manual of golems",
    "Manual of quickness of action",
    "Mirror of life trapping",
    "Nine lives stealer",
    "Oathbow",
    "Armor, +2 scale mail",
    "Spellguard shield",
    "Armor, +1 splint",
    "Armor of resistance (splint)",
    "Armor, +1 studded leather",
    "Armor of resistance (studded leather)",
    "Tome of clear thought",
    "Tome of leadership and influence",
    "Tome of understanding",
];

const magicTableI = [
    ...new Array(5).fill("Defender"),
    ...new Array(5).fill("Hammer of thunderbolts"),
    ...new Array(5).fill("Luck blade"),
    ...new Array(5).fill("Sword of answering"),
    ...new Array(3).fill("Holy avenger"),
    ...new Array(3).fill("Ring of djinni summoning"),
    ...new Array(3).fill("Ring of invisibility"),
    ...new Array(3).fill("Ring of spell turning"),
    ...new Array(3).fill("Rod of lordly might"),
    ...new Array(3).fill("Staff of the magi"),
    ...new Array(3).fill("Vorpal sword"),
    ...new Array(2).fill("Belt of cloud giant strength"),
    ...new Array(2).fill("Armor, +2 breastplate"),
    ...new Array(2).fill("Armor, +2 chain mail"),
    ...new Array(2).fill("Armor, +2 chain shirt"),
    ...new Array(2).fill("Cloak of invisibility"),
    ...new Array(2).fill("Crystal ball (legendary version)"),
    ...new Array(2).fill("Armor, +1 half plate"),
    ...new Array(2).fill("Iron flask"),
    ...new Array(2).fill("Armor, +3 leather"),
    ...new Array(2).fill("Armor, +1 plate"),
    ...new Array(2).fill("Robe of the archmagi"),
    ...new Array(2).fill("Rod of resurrection"),
    ...new Array(2).fill("Armor, +1 scale mail"),
    ...new Array(2).fill("Scarab of protection"),
    ...new Array(2).fill("Armor, +2 splint"),
    ...new Array(2).fill("Armor, +2 studded leather"),
    ...new Array(2).fill("Well of many worlds"),
    "Magic armor (1-2: +2 half plate, 3-4: +2 plate, 5-6: +3 studded leather, 7-8: +3 breastplate, 9-10: +3 splint, 11: +3 half plate, 12: +3 plate)",
    "Apparatus of Kwalish",
    "Armor of invulnerability",
    "Belt of storm giant strength",
    "Cubic gate",
    "Deck of many things",
    "Efreeti chain",
    "Armor of resistance (half plate)",
    "Horn of Valhalla (iron)",
    "Instrument of the bards (Ollamh harp)",
    "Ioun stone (greater absorption)",
    "Ioun stone (mastery)",
    "Ioun stone (regeneration)",
    "Plate armor of etherealness",
    "Armor of resistance (plate)",
    "Ring of air elemental command",
    "Ring of earth elemental command",
    "Ring of fire elemental command",
    "Ring of three wishes",
    "Ring of water elemental command",
    "Sphere of annihilation",
    "Talisman of pure good",
    "Talisman of the sphere",
    "Talisman of ultimate evil",
    "Tome of the stilled tongue",
];

const gems = {
    "10gp": [
        "Azurite (opaque mottled deep blue)",
        "Banded agate (translucent striped brown, blue, white, or red)",
        "Blue quartz (transparent pale blue)",
        "Eye agate (translucent circles of gray, white, brown, blue, or green)",
        "Hematite (opaque gray-black)",
        "Lapis lazuli (opaque light and dark blue with yellow flecks)",
        "Malachite (opaque striated light and dark green)",
        "Moss agate (translucent pink or yellow-white with mossy gray or green markings)",
        "Obsidian (opaque black)",
        "Rhodochrosite (opaque light pink)",
        "Tiger eye (translucent brown with golden center)",
        "Turquoise (opaque light blue-green)",
    ],
    "50gp": [
        "Bloodstone (opaque dark gray with red flecks)",
        "Carnelian (opaque orange to red-brown)",
        "Chalcedony (opaque white)",
        "Chrysoprase (translucent green)",
        "Citrine (transparent pale yellow-brown)",
        "Jasper (opaque blue, black, or brown)",
        "Moonstone (translucent white with pale blue glow)",
        "Onyx (opaque bands of black and white, or pure black or white)",
        "Quartz (transparent white, smoky gray, or yellow)",
        "Sardonyx (opaque bands of red and white)",
        "Star rose quartz (translucent rosy stone with white star-shaped center)",
        "Zircon (transparent pale blue-green)",
    ],
    "100gp": [
        "Amber (transparent watery gold to rich gold)",
        "Amethyst (transparent deep purple)",
        "Chrysoberyl (transparent yellow-green to pale green)",
        "Coral (opaque crimson)",
        "Garnet (transparent red, brown-green, or violet)",
        "Jade (translucent light green, deep green, or white)",
        "Jet (opaque deep black)",
        "Pearl (opaque lustrous white, yellow, or pink)",
        "Spinel (transparent red, red-brown, or deep green)",
        "Tourmaline (transparent pale green, blue, brown, or red)",
    ],
    "500gp": [
        "Alexandrite (transparent dark green)",
        "Aquamarine (transparent pale blue-green)",
        "Black pearl (opaque pure black)",
        "Blue spinel (transparent deep blue)",
        "Peridot (transparent rich olive green)",
        "Topaz (transparent golden yellow)",
    ],
    "1000gp": [
        "Black opal (translucent dark green with black mottling and golden flecks)",
        "Blue sapphire (transparent blue-white to medium blue)",
        "Emerald (transparent deep bright green)",
        "Fire opal (translucent fiery red)",
        "Opal (translucent pale blue with green and golden mottling)",
        "Star ruby (translucent ruby with white star-shaped center)",
        "Star sapphire (translucent blue sapphire with white star-shaped center)",
        "Yellow sapphire (transparent fiery yellow or yellow-green)",
    ],
    "5000gp": [
        "Black sapphire (translucent lustrous black with glowing highlights)",
        "Diamond (transparent blue-white, canary, pink, brown, or blue)",
        "Jacinth (transparent fiery orange)",
        "Ruby (transparent clear red to deep crimson)",
    ],
};

const art = {
    "25gp": [
        "Silver ewer",
        "Carved bone statuette",
        "Small gold bracelet",
        "Cloth-of-gold vestments",
        "Black velvet mask stitched with silver thread",
        "Copper chalice with silver filigree",
        "Pair of engraved bone dice",
        "Small mirror set in a painted wooden frame",
        "Embroidered silk handkerchief",
        "Gold locket with a painted portrait inside",
    ],
    "250gp": [
        "Gold ring set with bloodstones",
        "Carved ivory statuette",
        "Large gold bracelet",
        "Silver necklace with a gemstone pendant",
        "Bronze crown",
        "Silk robe with gold embroidery",
        "Large well-made tapestry",
        "Brass mug with jade inlay",
        "Box of turquoise animal figurines",
        "Gold bird cage with electrum filigree",
    ],
    "750gp": [
        "Silver chalice set with moonstones",
        "Silver-plated steel longsword with jet set in hilt",
        "Carved harp of exotic wood with ivory inlay and zircon gems",
        "Small gold idol",
        "Gold dragon comb set with red garnets as eyes",
        "Bottle stopper cork embossed with gold leaf and set with amethysts",
        "Ceremonial electrum dagger with a black pearl in the pommel",
        "Silver and gold brooch",
        "Obsidian statuette with gold fittings and inlay",
        "Painted gold war mask",
    ],
    "2500gp": [
        "Fine gold chain set with a fire opal",
        "Old masterpiece painting",
        "Embroidered silk and velvet mantle set with numerous moonstones",
        "Platinum bracelet set with a sapphire",
        "Embroidered glove set with jewel chips",
        "Jeweled anklet",
        "Gold music box",
        "Gold circlet set with four aquamarines",
        "Eye patch with a mock eye set in blue sapphire and moonstone",
        "A necklace string of small pink pearls",
    ],
    "7500gp": [
        "Jeweled gold crown",
        "Jeweled platinum ring",
        "Small gold statuette set with rubies",
        "Gold cup set with emeralds",
        "Gold jewelry box with platinum filigree",
        "Painted gold child’s sarcophagus",
        "Jade game board with solid gold playing pieces",
        "Bejeweled ivory drinking horn with gold filigree",
    ],
};

const hoardCoins = [
    // CR 0-4
    {"cp": "6d6x100", "sp": "3d6×100", "gp": "2d6×10"},
    // CR 5-10
    {"cp": "2d6x100", "sp": "2d6×1000", "gp": "6d6×100", "pp": "3d6x10"},
    // CR 11-16
    {"gp": "4d6×1000", "pp": "5d6x100"},
    // CR 17+
    {"gp": "12d6×1000", "pp": "8d6x1000"},
];

const hoardTable = [
    [ // CR 0-4
        ...new Array(6).fill([]), // 1-6
        ...new Array(10).fill([ // 7-16
            ["2d6", "Gem", gems["10gp"]],
        ]),
        ...new Array(10).fill([ // 17-26
            ["2d4", "Art", art["25gp"]],
        ]),
        ...new Array(10).fill([ // 27-36
            ["2d6", "Gem", gems["50gp"]],
        ]),
        ...new Array(8).fill([ // 37-44
            ["2d6", "Gem", gems["10gp"]],
            ["1d5", "Item", magicTableA],
        ]),
        ...new Array(8).fill([ // 45-52
            ["2d4", "Art", art["25gp"]],
            ["1d6", "Item", magicTableA],
        ]),
        ...new Array(8).fill([ // 53-60
            ["2d6", "Gem", gems["50gp"]],
            ["1d6", "Item", magicTableA],
        ]),
        ...new Array(5).fill([ // 61-65
            ["2d6", "Gem", gems["10gp"]],
            ["1d4", "Item", magicTableB],
        ]),
        ...new Array(5).fill([ // 66-70
            ["2d4", "Art", art["25gp"]],
            ["1d4", "Item", magicTableB],
        ]),
        ...new Array(5).fill([ // 71-75
            ["2d6", "Gem", gems["50gp"]],
            ["1d4", "Item", magicTableB],
        ]),
        ...new Array(3).fill([ // 76–78
            ["2d6", "Gem", gems["10gp"]],
            ["1d4", "Item", magicTableC],
        ]),
        ...new Array(2).fill([ // 79–80
            ["2d4", "Art", art["25gp"]],
            ["1d4", "Item", magicTableC],
        ]),
        ...new Array(5).fill([ // 81–85
            ["2d6", "Gem", gems["50gp"]],
            ["1d4", "Item", magicTableC],
        ]),
        ...new Array(7).fill([ // 86–92
            ["2d4", "Art", art["25gp"]],
            ["1d4", "Item", magicTableF],
        ]),
        ...new Array(5).fill([ // 93–97
            ["2d6", "Gem", gems["50gp"]],
            ["1d4", "Item", magicTableF],
        ]),
        ...new Array(2).fill([ // 98–99
            ["2d6", "Art", art["25gp"]],
            ["d1", "Item", magicTableG],
        ]),
        [ // 00
            ["2d6", "Gem", gems["50gp"]],
            ["d1", "Item", magicTableG],
        ],
    ],
    [ // CR 5-10
        ...new Array(4).fill([]), // 1-4
        ...new Array(6).fill([ // 05–10
            ["2d4", "Art", art["25gp"]],
        ]),
        ...new Array(6).fill([ // 11–16
            ["3d6", "Gem", gems["50gp"]],
        ]),
        ...new Array(6).fill([ // 17–22
            ["3d6", "Gem", gems["100gp"]],
        ]),
        ...new Array(6).fill([ // 23–28
            ["2d4", "Art", art["250gp"]],
        ]),
        ...new Array(4).fill([ // 29–32
            ["2d4", "Art", art["25gp"]],
            ["1d6", "Item", magicTableA],
        ]),
        ...new Array(4).fill([ // 33–36
            ["3d6", "Gem", gems["50gp"]],
            ["1d6", "Item", magicTableA],
        ]),
        ...new Array(4).fill([ // 37–40
            ["3d6", "Gem", gems["100gp"]],
            ["1d6", "Item", magicTableA],
        ]),
        ...new Array(4).fill([ // 41–44
            ["2d4", "Art", art["250gp"]],
            ["1d6", "Item", magicTableA],
        ]),
        ...new Array(5).fill([ // 45–49
            ["2d4", "Art", art["25gp"]],
            ["1d4", "Item", magicTableB],
        ]),
        ...new Array(5).fill([ // 50–54
            ["3d6", "Gem", gems["50gp"]],
            ["1d4", "Item", magicTableB],
        ]),
        ...new Array(5).fill([ // 55–59
            ["3d6", "Gem", gems["100gp"]],
            ["1d4", "Item", magicTableB],
        ]),
        ...new Array(4).fill([ // 60–63
            ["2d4", "Art", art["250gp"]],
            ["1d4", "Item", magicTableB],
        ]),
        ...new Array(3).fill([ // 64–66
            ["2d4", "Art", art["25gp"]],
            ["1d4", "Item", magicTableC],
        ]),
        ...new Array(3).fill([ // 67–69
            ["3d6", "Gem", gems["50gp"]],
            ["1d4", "Item", magicTableC],
        ]),
        ...new Array(3).fill([ // 70–72
            ["3d6", "Gem", gems["100gp"]],
            ["1d4", "Item", magicTableC],
        ]),
        ...new Array(2).fill([ // 73–74
            ["2d4", "Art", art["250gp"]],
            ["1d4", "Item", magicTableC],
        ]),
        ...new Array(2).fill([ // 75–76
            ["2d4", "Art", art["25gp"]],
            ["d1", "Item", magicTableD],
        ]),
        ...new Array(2).fill([ // 77–78
            ["3d6", "Gem", gems["50gp"]],
            ["d1", "Item", magicTableD],
        ]),
        [ // 79
            ["3d6", "Gem", gems["100gp"]],
            ["d1", "Item", magicTableD],
        ],
        [ // 80
            ["2d4", "Art", art["250gp"]],
            ["d1", "Item", magicTableD],
        ],
        ...new Array(4).fill([ // 81–84
            ["2d4", "Art", art["25gp"]],
            ["1d4", "Item", magicTableF],
        ]),
        ...new Array(4).fill([ // 85–88
            ["3d6", "Gem", gems["50gp"]],
            ["1d4", "Item", magicTableF],
        ]),
        ...new Array(3).fill([ // 89–91
            ["3d6", "Gem", gems["100gp"]],
            ["1d4", "Item", magicTableF],
        ]),
        ...new Array(3).fill([ // 92–94
            ["2d4", "Art", art["250gp"]],
            ["1d4", "Item", magicTableF],
        ]),
        ...new Array(2).fill([ // 95–96
            ["3d6", "Gem", gems["100gp"]],
            ["1d4", "Item", magicTableG],
        ]),
        ...new Array(2).fill([ // 97–98
            ["2d4", "Art", art["250gp"]],
            ["1d4", "Item", magicTableG],
        ]),
        [ // 99
            ["3d6", "Gem", gems["100gp"]],
            ["d1", "Item", magicTableH],
        ],
        [ // 00
            ["2d4", "Art", art["250gp"]],
            ["d1", "Item", magicTableH],
        ],
    ],
    [ // CR 11-16
        ...new Array(3).fill([]), // 1-3
        ...new Array(3).fill([ // 4-6
            ["2d4", "Art", art["250gp"]],
        ]),
        ...new Array(3).fill([ // 7-9
            ["2d4", "Art", art["750gp"]],
        ]),
        ...new Array(3).fill([ // 10-12
            ["3d6", "Gem", gems["500gp"]],
        ]),
        ...new Array(3).fill([ // 13-15
            ["3d6", "Gem", gems["500gp"]],
        ]),
        ...new Array(4).fill([ // 16-19
            ["2d4", "Art", art["250gp"]],
            ["1d4", "Item", magicTableA],
            ["1d6", "Item", magicTableB],
        ]),
        ...new Array(4).fill([ // 20-23
            ["2d4", "Art", art["750gp"]],
            ["1d4", "Item", magicTableA],
            ["1d6", "Item", magicTableB],
        ]),
        ...new Array(3).fill([ // 24-26
            ["3d6", "Gem", gems["500gp"]],
            ["1d4", "Item", magicTableA],
            ["1d6", "Item", magicTableB],
        ]),
        ...new Array(3).fill([ // 27-29
            ["3d6", "Gem", gems["1000gp"]],
            ["1d4", "Item", magicTableA],
            ["1d6", "Item", magicTableB],
        ]),
        ...new Array(6).fill([ // 30-35
            ["2d4", "Art", art["250gp"]],
            ["1d6", "Item", magicTableC],
        ]),
        ...new Array(5).fill([ // 36-40
            ["2d4", "Art", art["750gp"]],
            ["1d6", "Item", magicTableC],
        ]),
        ...new Array(5).fill([ // 41-45
            ["3d6", "Gem", gems["500gp"]],
            ["1d6", "Item", magicTableC],
        ]),
        ...new Array(5).fill([ // 46-50
            ["3d6", "Gem", gems["1000gp"]],
            ["1d6", "Item", magicTableC],
        ]),
        ...new Array(4).fill([ // 51-54
            ["2d4", "Art", art["250gp"]],
            ["1d4", "Item", magicTableD],
        ]),
        ...new Array(4).fill([ // 55-58
            ["2d4", "Art", art["750gp"]],
            ["1d4", "Item", magicTableD],
        ]),
        ...new Array(4).fill([ // 59-62
            ["3d6", "Gem", gems["500gp"]],
            ["1d4", "Item", magicTableD],
        ]),
        ...new Array(4).fill([ // 63-66
            ["3d6", "Gem", gems["1000gp"]],
            ["1d4", "Item", magicTableD],
        ]),
        ...new Array(2).fill([ // 67–68
            ["2d4", "Art", art["250gp"]],
            ["d1", "Item", magicTableE],
        ]),
        ...new Array(2).fill([ // 69–70
            ["2d4", "Art", art["750gp"]],
            ["d1", "Item", magicTableE],
        ]),
        ...new Array(2).fill([ // 71–72
            ["3d6", "Gem", gems["500gp"]],
            ["d1", "Item", magicTableE],
        ]),
        ...new Array(2).fill([ // 73–74
            ["3d6", "Gem", gems["1000gp"]],
            ["d1", "Item", magicTableE],
        ]),
        ...new Array(2).fill([ // 75–76
            ["2d4", "Art", art["250gp"]],
            ["d1", "Item", magicTableF],
            ["1d4", "Item", magicTableG],
        ]),
        ...new Array(2).fill([ // 77–78
            ["2d4", "Art", art["750gp"]],
            ["d1", "Item", magicTableF],
            ["1d4", "Item", magicTableG],
        ]),
        ...new Array(2).fill([ // 79–80
            ["3d6", "Gem", gems["500gp"]],
            ["d1", "Item", magicTableF],
            ["1d4", "Item", magicTableG],
        ]),
        ...new Array(2).fill([ // 81–82
            ["3d6", "Gem", gems["1000gp"]],
            ["d1", "Item", magicTableF],
            ["1d4", "Item", magicTableG],
        ]),
        ...new Array(3).fill([ // 83–85
            ["2d4", "Art", art["250gp"]],
            ["1d4", "Item", magicTableH],
        ]),
        ...new Array(3).fill([ // 86–88
            ["2d4", "Art", art["7500gp"]],
            ["1d4", "Item", magicTableH],
        ]),
        ...new Array(2).fill([ // 89–90
            ["3d6", "Gem", gems["500gp"]],
            ["1d4", "Item", magicTableH],
        ]),
        ...new Array(2).fill([ // 91–92
            ["3d6", "Gem", gems["1000gp"]],
            ["1d4", "Item", magicTableH],
        ]),
        ...new Array(2).fill([ // 93–94
            ["2d4", "Art", art["250gp"]],
            ["d1", "Item", magicTableI],
        ]),
        ...new Array(2).fill([ // 95–96
            ["2d4", "Art", art["750gp"]],
            ["d1", "Item", magicTableI],
        ]),
        ...new Array(2).fill([ // 97–98
            ["3d6", "Gem", gems["500gp"]],
            ["d1", "Item", magicTableI],
        ]),
        ...new Array(2).fill([ // 99–00
            ["3d6", "Gem", gems["1000gp"]],
            ["d1", "Item", magicTableI],
        ]),
    ],
    [ // CR 17+
        ...new Array(2).fill([]), // 01–02
        ...new Array(3).fill([ // 03–05
            ["3d6", "Gem", gems["1000gp"]],
            ["1d8", "Item", magicTableC],
        ]),
        ...new Array(3).fill([ // 06–08
            ["1d10", "Art", art["2500gp"]],
            ["1d8", "Item", magicTableC],
        ]),
        ...new Array(3).fill([ // 09–11
            ["1d4", "Art", art["7500gp"]],
            ["1d8", "Item", magicTableC],
        ]),
        ...new Array(3).fill([ // 12–14
            ["1d8", "Gem", gems["5000gp"]],
            ["1d8", "Item", magicTableC],
        ]),
        ...new Array(8).fill([ // 15–22
            ["3d6", "Gem", gems["1000gp"]],
            ["1d6", "Item", magicTableD],
        ]),
        ...new Array(8).fill([ // 23–30
            ["1d10", "Art", art["2500gp"]],
            ["1d6", "Item", magicTableD],
        ]),
        ...new Array(8).fill([ // 31–38
            ["1d4", "Art", art["7500gp"]],
            ["1d6", "Item", magicTableD],
        ]),
        ...new Array(8).fill([ // 39–46
            ["1d8", "Gem", gems["5000gp"]],
            ["1d6", "Item", magicTableD],
        ]),
        ...new Array(6).fill([ // 47–52
            ["3d6", "Gem", gems["1000gp"]],
            ["1d6", "Item", magicTableE],
        ]),
        ...new Array(6).fill([ // 53–58
            ["1d10", "Art", art["2500gp"]],
            ["1d6", "Item", magicTableE],
        ]),
        ...new Array(5).fill([ // 59–63
            ["1d4", "Art", art["7500gp"]],
            ["1d6", "Item", magicTableE],
        ]),
        ...new Array(5).fill([ // 64–68
            ["1d8", "Gem", gems["5000gp"]],
            ["1d6", "Item", magicTableE],
        ]),
        [ // 69
            ["3d6", "Gem", gems["1000gp"]],
            ["1d4", "Item", magicTableG],
        ],
        [ // 70
            ["1d10", "Art", art["2500gp"]],
            ["1d4", "Item", magicTableG],
        ],
        [ // 71
            ["1d4", "Art", art["7500gp"]],
            ["1d4", "Item", magicTableG],
        ],
        [ // 72
            ["1d8", "Gem", gems["5000gp"]],
            ["1d4", "Item", magicTableG],
        ],
        ...new Array(2).fill([ // 73–74
            ["3d6", "Gem", gems["1000gp"]],
            ["1d4", "Item", magicTableH],
        ]),
        ...new Array(2).fill([ // 75–76
            ["1d10", "Art", art["2500gp"]],
            ["1d4", "Item", magicTableH],
        ]),
        ...new Array(2).fill([ // 77–78
            ["1d4", "Art", art["7500gp"]],
            ["1d4", "Item", magicTableH],
        ]),
        ...new Array(2).fill([ // 79–80
            ["1d8", "Gem", gems["5000gp"]],
            ["1d4", "Item", magicTableH],
        ]),
        ...new Array(5).fill([ // 81–85
            ["3d6", "Gem", gems["1000gp"]],
            ["1d4", "Item", magicTableI],
        ]),
        ...new Array(5).fill([ // 86–90
            ["1d10", "Art", art["2500gp"]],
            ["1d4", "Item", magicTableI],
        ]),
        ...new Array(5).fill([ // 91–95
            ["1d4", "Art", art["7500gp"]],
            ["1d4", "Item", magicTableI],
        ]),
        ...new Array(5).fill([ // 96–00
            ["1d8", "Gem", gems["5000gp"]],
            ["1d4", "Item", magicTableI],
        ]),
    ],
];

export default class extends Command {
    constructor(client) {
        super(client, {
            name: "treasure",
            description: "Determine the treasure found.",
        });
    }

    async run(message, args) {
        const input = String(args._[0]);
        const hoard = input.startsWith("!");
        const cr = Number(input.replace(/^!/, ""));
        const d100 = args._[1] || roll("d100");
        if (isNaN(cr) || cr < 0) {
            throw new TypeError("please give me a CR");
        }

        let msg = "You found:";

        const coins: Record<string, string> = hoard
            ? hoardCoins[ratingIndex(cr)]
            : individualTable[ratingIndex(cr)][d100 - 1];
        for (const [key, value] of Object.entries(coins)) {
            msg += `\n* ${roll(value)} ${key}`
        }

        const items = hoard ? hoardTable[ratingIndex(cr)][d100 - 1] : [];
        for (const [key, type, value] of items) {
            for (let index = 0; index < roll(key); index++) {
                msg += `\n* ${type}: ${rand(value)}`;
            }
        }

        message.channel.send(msg);
    }
}
